# ota/pubkey.py -- TRUSTED CORE. Generated by tools/keygen.py.
#
# This is the root of trust for over-the-air updates. It is public, so it
# is fine to commit, but if it is wrong when you copy it over USB then
# every later signature check is meaningless.

N = int(
    "b9374db3183290f45839a031cb0b828e9c0c076d3763434cc770b46e90e11b02"
    "d67863a502be5aafaf621df6624d5ef076b5a732ac4014abb9538b6698dcdc97"
    "0151076a75bafb18bf6472188147c7ad978af3016c3556d6a3cb079a504ff679"
    "da0b159c36deba0288a7c5d44e490a5c9c6f782862cebd92a5d9430150faae6c"
    "45bca9485fa5631e6d6d93ffe2d47416a05d8c3d6eae82c0558d07d0cfa10d08"
    "8cc898d2b171662718ef62f0d21a1c7fbcce8516a53d9a8b44526a0fb59fd63c"
    "ef0737a50032939b475c0edb20010000809bc81235d9f0b1e5861998cf8a6f3c"
    "45b2d130812a229acf13b139b41c8d659bfaac8f0438fb9054d9e763e6d17241",
    16,
)

E = 65537
