#!/usr/bin/env python3
"""Generate an OTA signing keypair and the matching device public key module.

    python3 tools/keygen.py

Writes:
    ota-private.pem   your signing key -- KEEP THIS OUT OF THE REPO
    ota/pubkey.py     the modulus, baked into the device via USB

Keep ota-private.pem offline if you want a GitHub compromise to stop short of
code execution on the device. Put it in an Actions secret instead if you would
rather every tag push publish automatically.
"""
import pathlib
import sys

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import rsa

ROOT = pathlib.Path(__file__).resolve().parent.parent
PRIV = ROOT / "ota-private.pem"

if PRIV.exists():
    sys.exit(f"{PRIV} already exists; refusing to overwrite an existing key")

key = rsa.generate_private_key(public_exponent=65537, key_size=2048)

PRIV.write_bytes(
    key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    )
)
PRIV.chmod(0o600)

n = key.public_key().public_numbers().n
hexn = f"{n:x}"
lines = [hexn[i : i + 64] for i in range(0, len(hexn), 64)]
body = "\n".join(f'    "{ln}"' for ln in lines)

(ROOT / "ota" / "pubkey.py").write_text(
    "# ota/pubkey.py -- TRUSTED CORE. Generated by tools/keygen.py.\n"
    "#\n"
    "# This is the root of trust for over-the-air updates. It is public, so it\n"
    "# is fine to commit, but if it is wrong when you copy it over USB then\n"
    "# every later signature check is meaningless.\n"
    "\n"
    "N = int(\n"
    f"{body},\n"
    "    16,\n"
    ")\n"
    "\n"
    "E = 65537\n"
)

print(f"wrote {PRIV}")
print(f"wrote {ROOT / 'ota' / 'pubkey.py'}")
print("\nAdd ota-private.pem to .gitignore before your next commit.")